name: dev_overlay
description: "A draggable debug overlay for Flutter apps. Shows route, screen size, theme, FPS, device and app version info during development."
version: 1.0.2
homepage: https://github.com/Rasel2510/dev_overlay
repository: https://github.com/Rasel2510/dev_overlay
issue_tracker: https://github.com/Rasel2510/dev_overlay/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ">=10.1.0 <11.0.0"
  device_info_plus:  ">=13.1.0 <14.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.0"

topics:
  - debug
  - developer
  - inspector
  - overlay
  - flutter

flutter:
  uses-material-design: true
